### ISSUE TITLE
Error when running `ols login`

### ISSUE THREAD

**Issue by aymdoth** [moritzgloeckl/overleaf-sync#33]
Error when running `ols login`:

```
Traceback (most recent call last):
  File "/Users/hal/opt/anaconda3/bin/ols", line 5, in <module>
    from olsync.olsync import main
  File "/Users/hal/opt/anaconda3/lib/python3.8/site-packages/olsync/olsync.py", line 48, in <module>
    def main(ctx, local, remote, project_name, cookie_path, sync_path, olignore_path, verbose):
  File "/Users/hal/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "/Users/hal/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/hal/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

Details : 
```
macOS big sur
Python 3.8.3
pip 21.1.1
```

**Comment by zzjjzzgggg** [comment]
update your `click` package (e.g., by `pip install -U click`). The `click 8.0.0` package has some big change (see https://github.com/pallets/click/pull/1912#issue-647223378).

**Comment by aymdoth** [comment]
It worked. I should have tried this right away. Thanks! Now I can enjoy this super tool.
