### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'package_name'

### ISSUE THREAD

**Issue by lilianmallardeau** [moritzgloeckl/overleaf-sync#35]
I got the following error when trying the command `ols`:
```
Traceback (most recent call last):
  File "~/.local/bin/ols", line 5, in <module>
    from olsync.olsync import main
  File "~/.local/lib/python3.8/site-packages/olsync/olsync.py", line 48, in <module>
    def main(ctx, local, remote, project_name, cookie_path, sync_path, olignore_path, verbose):
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```
I use Python 3.8.10 and `overleaf-sync` latest version at this date, i.e. version 1.1.5.

**Comment by paulflang** [comment]
same here.

**Comment by mstou** [comment]
I have the same problem.

I found out that commenting out line 46 in olsync.py seems to fix the problem for now, but I hope it doesn't
cause any unintended behavior.

Until the devs can take a look at this, you can comment out this line https://github.com/moritzgloeckl/overleaf-sync/blob/4b77df9e04a762e2e14ad8812322e6c7663fa296/olsync/olsync.py#L46

**Comment by lilianmallardeau** [comment]
Yeah it works like this! Thanks
