### ISSUE TITLE
no olclient?

### ISSUE THREAD

**Issue by boyanpenkov** [moritzgloeckl/overleaf-sync#54]
``ols`` on a repo that functioned a few months ago now yields:

```
Traceback (most recent call last):
  File "/home/boyan/miniconda3/envs/python39/lib/python3.9/site-packages/olsync/olsync.py", line 26, in <module>
    import olsync.olbrowserlogin as olbrowserlogin
  File "/home/boyan/miniconda3/envs/python39/lib/python3.9/site-packages/olsync/olbrowserlogin.py", line 14, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: /usr/lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol: uuid_generate_sha1, version UUID_2.31

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boyan/miniconda3/envs/python39/bin/ols", line 5, in <module>
    from olsync.olsync import main
  File "/home/boyan/miniconda3/envs/python39/lib/python3.9/site-packages/olsync/olsync.py", line 29, in <module>
    from olclient import OverleafClient
ModuleNotFoundError: No module named 'olclient'
make: *** [makefile:18: sync] Error 1

```

This is after I do a fresh pip3 install.  Anybody else see this?

**Comment by moritzgloeckl** [comment]
It seems something got messed up when you reinstalled pip3... I haven't seen anything like that yet and I don't think it's a problem with `ols`. Feel free to comment again if you notice any more issues.

**Comment by kgtkr** [comment]
I fixed it by doing `sudo apt install libasound2`
