### ISSUE TITLE
Error: Project details could not be queried.

### ISSUE THREAD

**Issue by LuckyJinging** [moritzgloeckl/overleaf-sync#61]
I can obtain the project list with `ols list`, but I got an error when I do `ols -l ` or `ols -r` to sync files.

Project queried successfully.
✅  Querying project
💥  Querying project details
Error: Project details could not be queried.

**Comment by saran-ravi** [comment]
Same problem here, I could not download the project files

**Comment by freerkschuett** [comment]
Yup, same problem. `ols list` works, but just `ols` fails with `Error: Project details could not be queried.`

**Comment by elonhub** [comment]
Same here, more info:
```
> ols -v -n 'PROJECT' -r
Project queried successfully.
✅  Querying project
⠋ Querying project detailsTraceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/olsync/olsync.py", line 348, in execute_action
    success = action()
  File "/home/user/.local/lib/python3.10/site-packages/olsync/olsync.py", line 73, in <lambda>
    lambda: overleaf_client.get_project_infos(project["id"]),
  File "/home/user/.local/lib/python3.10/site-packages/olsync/olclient.py", line 167, in get_project_infos
    self._cookie["GCLB"],
KeyError: 'GCLB'

💥  Querying project details
Error: Project details could not be queried.
```
That line reads:

```
    164         # Convert cookie from CookieJar to string
    165         cookie = "GCLB={}; overleaf_session2={}" \
    166             .format(
    167             self._cookie["GCLB"],
    168             self._cookie["overleaf_session2"]
    169         )

```

That self._cookie would probably need to come from OverleafClient.login() which states, that its DEPRECATED.
I hope that helps a bit.

**Comment by liamoconnor9** [comment]
Same issue, itstorque's commit remedied this after generating a new login cookie

**Comment by CeciliaCoelho** [comment]
After getting the same error itstorque's commit fixed it but today a different error message appeared. Using linux

```
 >> ols login 
Persisted Overleaf cookie already exist. Do you want to override it? [y/N]: y
⠸ Loginjs: Uncaught TypeError: Cannot read properties of undefined (reading 'href')
js: Uncaught TypeError: Cannot read properties of undefined (reading 'content')
Login successful. Cookie persisted as `.olauth`. You may now sync your project.
✅  Login

>> ols -r 
💥  Querying project
Error: Project could not be queried.
```

**Comment by svennniiii** [comment]
Hi @CeciliaCoelho, @itstorque's  commit also stopped working for me. It seems Overleaf has made some changes on the website. These modifications (see #66) worked for me.

**Comment by itstorque** [comment]
Took a look at the rendered HTML for the landing page, they removed the classes for the links in the table. I think replacing the line 
```javascript
JAVASCRIPT_EXTRACT_PROJECT_URL = "document.getElementsByClassName('project-list-table-name-link')[0].href"
```
with this
```javascript
JAVASCRIPT_EXTRACT_PROJECT_URL = "document.getElementsByTagName('tbody')[0].children[0].getElementsByTagName('a')[0].href"
```
should work. Its very jank, if they introduce another table in the HTML before the project list, it will break.

Another possible implementation that I prefer would be replacing that line with
```javascript
JAVASCRIPT_EXTRACT_PROJECT_URL = "q=0;for (const c of document.getElementsByTagName('a')) { if(c.href.indexOf('/project/') > 0) { q=c.href; break; } }; q"
```
The thinking here is that support for URLs is more concrete (backcompatibility) and therefore changes to the html page wouldn't break the ability to find a link to a project to load the GCLB cookie.

Note: I didn't test these, but I am confident that they should work (lmk otherwise)

**Comment by svennniiii** [comment]
I think this alone doesn't do the trick. Additionally, I had to do two changes in `class OverleafClient(object)` in the methods that deal with querying the project (`def all_projects(self)` and `def get_project(self)`). (see #66) 

I don't know how the old landing page looked like, but it may be due to the same design changes.

**Comment by D-VR** [comment]
~~I replaced the files in the pip module with the fixes from the linked repository in #66, but I am getting the following issue using `ols download -v` (with a fresh login token)~~


```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/olsync/olsync.py", line 354, in execute_action
    success = action()
              ^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/olsync/olsync.py", line 179, in download_project_pdf
    project = execute_action(
              ^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/olsync/olsync.py", line 365, in execute_action
    raise click.ClickException(fail_message)
click.exceptions.ClickException: Project could not be queried.

💥  Downloading project's PDF
Error: Downloading project's PDF failed. Please try again.
```
### EDIT:

**User error,** I forgot to select the project I want to sync / download.

correct command to do is: `ols download -n my_project`  the fix works perfectly!

**Comment by naufalmuafi** [comment]
Hello,

I'm encountering an issue when trying to query project details using overleaf-sync. After initiating the query, I receive an error related to the WebSocket connection. The connection to the remote host is unexpectedly closed, which leads to a WebSocketConnectionClosedException. Following this, another error occurs where the script attempts to handle an SSLError in the websocket module, but it results in an AttributeError, stating that the module 'websocket' has no attribute 'SSLError'. This issue is preventing me from successfully querying project details.

```
⠧ Querying project detailsTraceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\transports.py", line 175, in recv
    yield self._connection.recv()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 388, in recv
    opcode, data = self.recv_data()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 416, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 437, in recv_data_frame
    frame = self.recv_frame()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 478, in recv_frame
    return self.frame_buffer.recv_frame()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_abnf.py", line 363, in recv_frame
    self.recv_header()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_abnf.py", line 319, in recv_header
    header = self.recv_strict(2)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_abnf.py", line 398, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 563, in _recv
    return recv(self.sock, bufsize)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_socket.py", line 132, in recv
    raise WebSocketConnectionClosedException("Connection to remote host was lost.")
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\olsync\olsync.py", line 354, in execute_action
    success = action()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\olsync\olsync.py", line 73, in <lambda>
    lambda: overleaf_client.get_project_infos(project["id"]),
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\olsync\olclient.py", line 185, in get_project_infos
    socket_io.wait_for_callbacks()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\__init__.py", line 292, in wait_for_callbacks
    self.wait(seconds, for_callbacks=True)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\__init__.py", line 254, in wait
    self._process_events(timeout)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\__init__.py", line 271, in _process_events
    for packet in self._transport.recv_packet(timeout):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\transports.py", line 99, in recv_packet
    for packet_text in self.recv(timeout=timeout):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\transports.py", line 178, in recv
    except websocket.SSLError as e:
AttributeError: module 'websocket' has no attribute 'SSLError'
```

Any guidance or updates on how to resolve this would be greatly appreciated.

**Comment by naufalmuafi** [comment]
> Hello,
> 
> I'm encountering an issue when trying to query project details using overleaf-sync. After initiating the query, I receive an error related to the WebSocket connection. The connection to the remote host is unexpectedly closed, which leads to a WebSocketConnectionClosedException. Following this, another error occurs where the script attempts to handle an SSLError in the websocket module, but it results in an AttributeError, stating that the module 'websocket' has no attribute 'SSLError'. This issue is preventing me from successfully querying project details.
> 
> ```
> ⠧ Querying project detailsTraceback (most recent call last):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\transports.py", line 175, in recv
>     yield self._connection.recv()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 388, in recv
>     opcode, data = self.recv_data()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 416, in recv_data
>     opcode, frame = self.recv_data_frame(control_frame)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 437, in recv_data_frame
>     frame = self.recv_frame()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 478, in recv_frame
>     return self.frame_buffer.recv_frame()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_abnf.py", line 363, in recv_frame
>     self.recv_header()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_abnf.py", line 319, in recv_header
>     header = self.recv_strict(2)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_abnf.py", line 398, in recv_strict
>     bytes_ = self.recv(min(16384, shortage))
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_core.py", line 563, in _recv
>     return recv(self.sock, bufsize)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\websocket\_socket.py", line 132, in recv
>     raise WebSocketConnectionClosedException("Connection to remote host was lost.")
> websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\olsync\olsync.py", line 354, in execute_action
>     success = action()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\olsync\olsync.py", line 73, in <lambda>
>     lambda: overleaf_client.get_project_infos(project["id"]),
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\olsync\olclient.py", line 185, in get_project_infos
>     socket_io.wait_for_callbacks()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\__init__.py", line 292, in wait_for_callbacks
>     self.wait(seconds, for_callbacks=True)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\__init__.py", line 254, in wait
>     self._process_events(timeout)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\__init__.py", line 271, in _process_events
>     for packet in self._transport.recv_packet(timeout):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\transports.py", line 99, in recv_packet
>     for packet_text in self.recv(timeout=timeout):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\socketIO_client\transports.py", line 178, in recv
>     except websocket.SSLError as e:
> AttributeError: module 'websocket' has no attribute 'SSLError'
> ```
> 
> Any guidance or updates on how to resolve this would be greatly appreciated.

okay, it's working with [this issue comment](https://github.com/moritzgloeckl/overleaf-sync/issues/78#issuecomment-1998419137)
