### ISSUE TITLE
Stopped working last week

### ISSUE THREAD

**Issue by CeciliaCoelho** [moritzgloeckl/overleaf-sync#78]
Hi everyone,

Last week sync stopped working. Tried login again and everything goes fine but then when pulling from remote it gives an error. Tried with several projects and the same happens:

```
Persisted Overleaf cookie already exist. Do you want to override it? [y/N]: y
Login successful. Cookie persisted as `.olauth`. You may now sync your project.
✅  Login
``` 

```
Project queried successfully.
✅  Querying project
💥  Querying project details
Error: Project details could not be queried.
```

**Comment by OLaurent** [comment]
Same issue on my side:
```shell
Project queried successfully.
✅  Querying project
⠸ Querying project detailsTraceback (most recent call last):
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/transports.py", line 175, in recv
    yield self._connection.recv()
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 362, in recv
    opcode, data = self.recv_data()
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 385, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/olsync/olsync.py", line 348, in execute_action
    success = action()
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/olsync/olsync.py", line 73, in <lambda>
    lambda: overleaf_client.get_project_infos(project["id"]),
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/olsync/olclient.py", line 186, in get_project_infos
    socket_io.wait_for_callbacks()
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/__init__.py", line 292, in wait_for_callbacks
    self.wait(seconds, for_callbacks=True)
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/__init__.py", line 254, in wait
    self._process_events(timeout)
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/__init__.py", line 271, in _process_events
    for packet in self._transport.recv_packet(timeout):
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/transports.py", line 99, in recv_packet
    for packet_text in self.recv(timeout=timeout):
  File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/transports.py", line 178, in recv
    except websocket.SSLError as e:
AttributeError: module 'websocket' has no attribute 'SSLError'

```

**Comment by lxhoanghsgs** [comment]
> Same issue on my side:
> 
> ```shell
> Project queried successfully.
> ✅  Querying project
> ⠸ Querying project detailsTraceback (most recent call last):
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/transports.py", line 175, in recv
>     yield self._connection.recv()
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 362, in recv
>     opcode, data = self.recv_data()
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 385, in recv_data
>     opcode, frame = self.recv_data_frame(control_frame)
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 406, in recv_data_frame
>     frame = self.recv_frame()
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 445, in recv_frame
>     return self.frame_buffer.recv_frame()
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 338, in recv_frame
>     self.recv_header()
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 294, in recv_header
>     header = self.recv_strict(2)
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 373, in recv_strict
>     bytes_ = self.recv(min(16384, shortage))
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 529, in _recv
>     return recv(self.sock, bufsize)
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/websocket/_socket.py", line 122, in recv
>     raise WebSocketConnectionClosedException(
> websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/olsync/olsync.py", line 348, in execute_action
>     success = action()
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/olsync/olsync.py", line 73, in <lambda>
>     lambda: overleaf_client.get_project_infos(project["id"]),
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/olsync/olclient.py", line 186, in get_project_infos
>     socket_io.wait_for_callbacks()
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/__init__.py", line 292, in wait_for_callbacks
>     self.wait(seconds, for_callbacks=True)
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/__init__.py", line 254, in wait
>     self._process_events(timeout)
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/__init__.py", line 271, in _process_events
>     for packet in self._transport.recv_packet(timeout):
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/transports.py", line 99, in recv_packet
>     for packet_text in self.recv(timeout=timeout):
>   File "/Users/olivierlaurent/Library/Python/3.9/lib/python/site-packages/socketIO_client/transports.py", line 178, in recv
>     except websocket.SSLError as e:
> AttributeError: module 'websocket' has no attribute 'SSLError'
> ```

Same problem for me

**Comment by Usgupta** [comment]
same me too!

**Comment by Particle-cosmology** [comment]
Same issue for me!

**Comment by david-2031** [comment]
Same issue

**Comment by Vasissualiyp** [comment]
Did anyone fix this problem? Have the same issue

**Comment by ericsua** [comment]
I solved this problem by installing this fork [https://github.com/zzjjzzgggg/overleaf-sync](https://github.com/zzjjzzgggg/overleaf-sync). Credits to @zzjjzzgggg.

**Comment by lxhoanghsgs** [comment]
> I solved this problem by installing this fork https://github.com/zzjjzzgggg/overleaf-sync. Credits to @zzjjzzgggg.

Thank you! I used this fork from @zzjjzzgggg, but still got an error. The log is as follows.

Using project name: Chapter4_ControlTheory
[KProject queried successfully.
[K[?25h[32m✅ [0m Querying project
[32m⠋[0m Querying project details[?25hTraceback (most recent call last):
  File "C:\Users\MyPC\Python\overleaf-sync\olsync\olsync.py", line 442, in execute_action
    success = action()
  File "C:\Users\MyPC\Python\overleaf-sync\olsync\olsync.py", line 106, in <lambda>
    lambda: overleaf_client.get_project_infos(project["id"]),
  File "C:\Users\MyPC\Python\overleaf-sync\olsync\olclient.py", line 191, in get_project_infos
    self._cookie["GCLB"], self._cookie["overleaf_session2"])
KeyError: 'GCLB'

[K[?25h[32m💥 [0m Querying project details
Error: Project details could not be queried.

**Comment by CeciliaCoelho** [comment]
> I solved this problem by installing this fork https://github.com/zzjjzzgggg/overleaf-sync. Credits to @zzjjzzgggg.

Get this error when installing: 
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-iai251qp/olsync/__init__.py'
```

**Comment by lxhoanghsgs** [comment]
> > I solved this problem by installing this fork https://github.com/zzjjzzgggg/overleaf-sync. Credits to @zzjjzzgggg.
> 
> Get this error when installing:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-iai251qp/olsync/__init__.py'
> ```

It is because the file '__init__.py' is stored in the wrong directory. To solve this, you need to open the repo, you will see that there is a folder named "olsync" inside the folder "olsync". Move the files inside the smaller "olsync" folder to the bigger one, and you're done.

Best wishes!
